version: 3.9

services:
  django_project:
    build:
      dockerfile: Dockerfile
      context: .
    image: django_docker:latest
    container_name: django_banner_docker
    volumes:
      - static_volume:/django/static
      - media_volume:/django/media
    command: >
      bash -c "./manage.py collectstatic --noinput && ./manage.py makemigrations && ./manage.py migrate"  
      bash -c "./manage.py add_price && gunicorn -b 0.0.0.0:8000 mysite.wsgi:application"
    restart: always